# Generated by Django 6.0.4 on 2026-05-16 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_backfill_user_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('IMPORTANT_URGENT', 'important and urgent'), ('IMPORTANT_NOT_URGENT', 'important and not urgent'), ('NOT_IMPORTANT_URGENT', 'not important and urgent'), ('NOT_IMPORTANT_NOT_URGENT', 'not important and not urgent')], default='NOT_IMPORTANT_NOT_URGENT', max_length=24)),
                ('goal_subtype', models.CharField(choices=[('weekly_goal', 'Weekly Goal'), ('monthly_project', 'Monthly Project'), ('annual_project', 'Annual Project'), ('five_year_project', 'Five Year Project')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='users.userattribute')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
