name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: act # O la etiqueta que le hayas dado a tu runner
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          token: ${{ gitea.token }}
      - name: Construir la imagen de Docker
        run: |
          docker build -t productivity_back:latest .

      - name: Desplegar en producción
        run: |
          # Navegamos a la carpeta donde está el docker-compose de producción en el servidor
          # e indicamos que levante la nueva imagen construida.
          cd /home/devjdtpserver/Compartido/Productions/productivity-prod
          docker compose -f docker-compose.prod.yml up -d --build
          
          # Ejecutar migraciones y recolectar estáticos dentro del nuevo contenedor
          docker compose -f docker-compose.prod.yml exec -T web python manage.py migrate --noinput
          docker compose -f docker-compose.prod.yml exec -T web python manage.py collectstatic --noinput
      
