# Generated by Django 6.0.5 on 2026-05-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('IMPORTANT_URGENT', 'important and urgent'), ('IMPORTANT_NOT_URGENT', 'important and not urgent'), ('NOT_IMPORTANT_URGENT', 'not important and urgent'), ('NOT_IMPORTANT_NOT_URGENT', 'not important and not urgent')], default='NOT_IMPORTANT_NOT_URGENT', max_length=24),
        ),
    ]
