# Generated by Django 6.0.5 on 2026-05-16 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_priority'),
        ('users', '0002_userattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='users.userattribute'),
        ),
    ]
